name:                keylayouts
version:             0.1.0.0
synopsis:            Tools for macOS .keylayout files
description:         Datatypes, parsing, and printing for .keylayout files,
                     Used for advanced keyboard mappings on macOS.
                     https://developer.apple.com/library/archive/technotes/tn2056/_index.html
homepage:            https://github.com/githubuser/keylayouts#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - xeno
  - bytestring
  - pretty-simple
  - text
default-extensions:
  - LambdaCase
  - BlockArguments
  - StandaloneDeriving
  - FlexibleInstances
  - OverloadedStrings
  - PatternSynonyms
  - ViewPatterns

library:
    source-dirs:      src
    other-modules: XML
