name:                keylayouts
version:             0.1.0.2
synopsis:            Tools for macOS .keylayout files
description:         Datatypes, parsing, and printing for .keylayout files,
                     Used for advanced keyboard mappings on macOS.
                     https://developer.apple.com/library/archive/technotes/tn2056/_index.html
homepage:            https://github.com/daig/keylayouts#readme
license:             MIT
author:              Dai
maintainer:          daig@sodality.cc
copyright:           2020 Dai
category:            xml, configuration
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - xeno
  - bytestring
  - text
  - pretty-simple
default-extensions:
  - LambdaCase
  - BlockArguments
  - StandaloneDeriving
  - FlexibleInstances
  - OverloadedStrings
  - PatternSynonyms
  - ViewPatterns
  - NoImplicitPrelude
  - GeneralizedNewtypeDeriving
  - TypeApplications
  - DisambiguateRecordFields
  - DerivingStrategies

library:
    source-dirs:      src
    other-modules: Pre
